on:
  push:
    branches:
      - main

  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: yarn

      - run: yarn install --immutable

      - run: yarn validate:schema

      - run: yarn generate:json
      - name: Verify that `yarn generate:json` did not change outputs (if it did, please re-run it and re-commit!)
        run: git diff --exit-code

      - run: yarn validate:examples
