on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: Verify that `npm run build` did not change outputs
        run: git diff --exit-code

      - run: npm test
      - run: npm run lint
